### ISSUE TITLE
Where is the download linking of features_m_128.mat and features_m_128_gt.mat?

### ISSUE THREAD

**Issue by willard-yuan** [una-dinosauria/stacked-quantizers#1]
Hi jltmtz,
Recently I'm very interested in the **Stacked Quantizers**, and I want to run the code you provided, but     I find there is no download linking of `features_m_128.mat` and `features_m_128_gt.mat`. Would you like to provide the two `.mat` files for me?

**Comment by una-dinosauria** [comment]
Hi @willard-yuan! Thanks for pointing that out!

Here are the files
- [features_m_128.mat](https://drive.google.com/file/d/0BxWzojlLp259aUt4Z1ZCMzVDQlk/view?usp=sharing)
- [features_m_128_gt.mat](https://drive.google.com/file/d/0BxWzojlLp259cmJkeG40S3oxR28/view?usp=sharing)

I put them in google drive in the meantime. Let me know if that's a problem.

**Comment by willard-yuan** [comment]
Awesome, I'm really appreciate for your help. Thanks.
