### ISSUE TITLE
compile problem on MATLAB 2017a, macOS Sierra

### ISSUE THREAD

**Issue by kr11** [una-dinosauria/stacked-quantizers#2]
Thanks for this great work.
I notice it doesn't compile on OSX (using clang). My system is MacOS Sierra. Matlab version is R2017a.
When I ran compile.m, it gives these errors:
```
>>compile
Use "XCode Clang++" compiling
Error using mex 
clang: error: unsupported option '-fopenmp'

Error  compile (line 4)
mex linscan_aqd_knn_mex.cc linscan_aqd.cc -Iinclude CXXFLAGS="\$CXXFLAGS ...
```
Any ideas about this problem? Thanks,

**Comment by una-dinosauria** [comment]
Yes, I know exactly what is happening. g++ in mac actually calls clang++, and the default distribution of clang++ on macOS does not support openmp.

So, to fix this, follow this SO thread: https://stackoverflow.com/a/29109926/1884420

PS: `brew install gcc` will take like +1 hour. I just did it a few days ago on my mac.

**Comment by kr11** [comment]
Thank you so much for the speedy reply!  I install gcc and run `gcc -fopenmp hello.c` successfully in terminal.

Another question is, when I run `compile` in matlab, it still calls clang++ but not gcc. In matlab, How could I refer `gcc` to its correct command?

**Comment by una-dinosauria** [comment]
There is a config file for mex where you can specify what g++ it should call. Maybe have a look over here: https://www.mathworks.com/help/matlab/matlab_external/changing-default-compiler.html?s_tid=gn_loc_drop

**Comment by kr11** [comment]
I'm sorry for bothering you again. I specify gcc-7 by changing the configuration file `/Users/XXX/Library/Application Support/MathWorks/MATLAB/R2017b/mex_C++_maci64.xml`. I change two lines by replacing `clang` to `/usr/bin/local/gcc-7`:
![image](https://user-images.githubusercontent.com/5548915/35139542-8e4742c8-fd2e-11e7-85f0-a74d77254fbd.png)

It solves "-fopenmp" error but bring new errors:
```
error using mex
gcc-7: error: unrecognized command line option '-fobjc-arc'; did you mean '-fobjc-gc'?
gcc-7: error: unrecognized command line option '-stdlib=libc++'
```

**Comment by una-dinosauria** [comment]
Maybe CXX should point to `/usr/local/bin/g++-7`? It's c++, not c.

**Comment by kr11** [comment]
Thanks. I've gotten results of PQ and OPQ successfully on Ubuntu. But met new problem on running AQ and SQ. I open another [issue#3](https://github.com/una-dinosauria/stacked-quantizers/issues/3) and hope for your help.

Thanks for your kind answer again~
