### ISSUE TITLE
The recall of SQ is very low

### ISSUE THREAD

**Issue by xiaoshuiqing** [una-dinosauria/stacked-quantizers#4]
Dear Julieta,
Thanks for your great work .
Recently I'm very interested in the Stacked Quantizers. When I run PQ,OPQ,SQ part of this code, their recalls are all low(for example the recall is only 0.011 when  N=10000, Any ideas about this problem? T
Looking forward to your reply! Thanks~

**Comment by una-dinosauria** [comment]
Hi @xiaoshuiqing,

I have not used this code in a long time, and I stopped using matlab a long time ago.

You can run stacked quantizers on Julia, using [Rayuela.jl](https://github.com/una-dinosauria/Rayuela.jl)

**Comment by una-dinosauria** [comment]
I have added a deprecation notice to the README: 6a5cddaa74571f2887efcc927cd2bfdda7f9703a

**Comment by xiaoshuiqing** [comment]
OK，thank you very much~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Julieta Martinez"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月8日(星期一) 凌晨0:34
收件人:&nbsp;"una-dinosauria/stacked-quantizers"<stacked-quantizers@noreply.github.com&gt;;
抄送:&nbsp;"水青"<2316837634@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [una-dinosauria/stacked-quantizers] The recall of SQ is very low (#4)





 
Hi @xiaoshuiqing,
 
I have not used this code in a long time, and I stopped using matlab a long time ago.
 
You can run stacked quantizers on Julia, using Rayuela.jl
